### ISSUE TITLE
安装失败了  this fails on your system: ng serve

### ISSUE THREAD

**Issue by a532233648** [ElonH/RcloneNg#1]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle rclone-ng@0.3.0~prestart: rclone-ng@0.3.0
6 silly lifecycle rclone-ng@0.3.0~prestart: no script for prestart, continuing
7 info lifecycle rclone-ng@0.3.0~start: rclone-ng@0.3.0
8 verbose lifecycle rclone-ng@0.3.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle rclone-ng@0.3.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/root/softs/RcloneNg/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle rclone-ng@0.3.0~start: CWD: /root/softs/RcloneNg
11 silly lifecycle rclone-ng@0.3.0~start: Args: [ '-c', 'ng serve' ]
12 info lifecycle rclone-ng@0.3.0~start: Failed to exec start script
13 verbose stack Error: rclone-ng@0.3.0 start: `ng serve`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid rclone-ng@0.3.0
15 verbose cwd /root/softs/RcloneNg
16 error Linux 4.20.8-1.el7.elrepo.x86_64
17 error argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 error node v8.10.0
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error rclone-ng@0.3.0 start: `ng serve`
24 error spawn ENOENT
25 error Failed at the rclone-ng@0.3.0 start script 'ng serve'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the rclone-ng package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     ng serve
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs rclone-ng
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls rclone-ng
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by ElonH** [comment]
@a532233648 可能 node 和 npm 太旧了, 升级一下试试

**Comment by a532233648** [comment]
> @a532233648 可能 node 和 npm 太旧了, 升级一下试试

node v8.10.0, npm 6.14.5 是太旧了么？

**Comment by ElonH** [comment]
@a532233648 
我机器上的node是 v10.16.3, npm是 6.14.5,
actions上的node是12.

我也不清楚node v8版本是否真的能支持.

不过[stackoverflow](https://stackoverflow.com/questions/58927491/you-are-running-version-v8-9-3-of-node-js-which-is-not-supported-by-angular-cli) 上面提到nodev8是不支持 angular8+版本.

本项目使用angular9, 大概率是因为node太旧了吧

**Comment by a532233648** [comment]
> @a532233648
> 我机器上的node是 v10.16.3, npm是 6.14.5,
> actions上的node是12.
> 
> 我也不清楚node v8版本是否真的能支持.
> 
> 不过[stackoverflow](https://stackoverflow.com/questions/58927491/you-are-running-version-v8-9-3-of-node-js-which-is-not-supported-by-angular-cli) 上面提到nodev8是不支持 angular8+版本.
> 
> 本项目使用angular9, 大概率是因为node太旧了吧

好吧，多谢了
