### ISSUE TITLE
无法进入面板怎么修改地址？

### ISSUE THREAD

**Issue by CODYI1** [ElonH/RcloneNg#10]
设备；斐讯N1 Ubuntu 18.04
问题描述：RcloneNg已完成安装，但是由于Ubuntu没有浏览器，无法打开localhost:4200, 如何更改这个地址？并通过同一局域网下设备访问该地址。
![Screenshot_20201210-213333__01](https://user-images.githubusercontent.com/34393173/101780072-04820c00-3b31-11eb-9a77-600832eef3c9.jpg)

**Comment by ElonH** [comment]
只需要把release上的rcloneng放到nginx网站目录即可，运行不依赖于node
