### ISSUE TITLE
can we deploy to heroku?

### ISSUE THREAD

**Issue by askfriends** [ElonH/RcloneNg#7]
hi this seems to be very nice gui and very useful project.

can we deploy it to heroku to run it without local pc? it will be really helpful and w can run long operations.

**Comment by ElonH** [comment]
Hi,
I think RcloneNg can be deployed in heroku, even I never use it before.

But It is not very useful that deploying RcloneNg in heroku except that you develop RcloneNg. and I don't understand what long operations you needed.

**Comment by askfriends** [comment]
> Hi,
> I think RcloneNg can be deployed in heroku, even I never use it before.
> 
> But It is not very useful that deploying RcloneNg in heroku except that you develop RcloneNg. and I don't understand what long operations you needed.

Can you make it heroku compatible and write hoe to deploy it?
i have multiple tds for backup, and there are lot of music flacs so they take very long time to copy, thats why it will be really helpful to run copy command on heroku and leave it.

**Comment by ElonH** [comment]
@askfriends 

You misunderstand RcloneNg and Rclone.
RcloneNg is just pure client-side website, it control Rclone via [rc API](https://rclone.org/commands/rclone_rcd/)
You can treat RcloneNg as a wrapper for rc API.
RcloneNg doesn't store any user data into server.

So you should run Rclone in heroku rather RcloneNg.

And you can post massive tasks to your Rclone server (in heroku) via RcloneNg, then close RcloneNg website. The tasks still run in Rclone server. And you also use RcloneNg again to reconnect Rclone server and check the tasks progresses.

By the way, you directly use `https://elonh.github.io/RcloneNg` to control your Rclone server.

**Comment by askfriends** [comment]
> https://elonh.github.io/RcloneNg

thanks for clarifying that, and yeah i misunderstood like you said. i am using rclone locally and it sucks because i have limited and faulty internet service, keeps disconnecting and i cant switch at the moment because this is all we got in our area.

so i was thinking about the idea to run rclone on heroku and have gui like yours. so can you add rclone feature and heroku support too? that would be nice

**Comment by ElonH** [comment]
That is good idea. But I can't provide lots of help in heroku, cause I have no experience in heroku.
It is very useful that asking question in [Rclone forum](https://forum.rclone.org/).

**Comment by askfriends** [comment]
> That is good idea. But I can't provide lots of help in heroku, due to no experience in heroku.
> It is very useful that asking question in [Rclone forum](https://forum.rclone.org/).

i think there are already rclone repos available here for both heroku and accessed via telegram bot, so find one and do some changes necessary, i think it will not be hard for you just copy paste some files.

**Comment by ElonH** [comment]
@askfriends 
Do it yourself.
We are not obligated to work for you.

**Comment by askfriends** [comment]
> @askfriends
> Do it yourself.
> We are not obligated to work for you.

its not about me but for many. anyway thnk u
