### ISSUE TITLE
Gitpod

### ISSUE THREAD

**Issue by thehamkercat** [ElonH/RcloneNg#8]
How can i access the web ui? i deployed via gitpod.

**Comment by ElonH** [comment]
gitpod will automatically popup a notification.

![image](https://user-images.githubusercontent.com/32666230/94546387-647e4b80-0280-11eb-9e84-13d0d80143a5.png)

**Comment by thehamkercat** [comment]
> gitpod will automatically popup a notification.
> 
> ![image](https://user-images.githubusercontent.com/32666230/94546387-647e4b80-0280-11eb-9e84-13d0d80143a5.png)

Oh, got it
